"""Real-Prefect-server integration tests.

Skipped unless invoked with ``-m prefect_real``. Requires PREFECT_API_URL env
var pointing at a reachable Prefect 3.x server (LAN: http://192.168.2.182:4200/api,
or in CI: http://localhost:4200/api).

These tests intentionally bypass the prefect_test_harness so they exercise the
real REST API + state transitions that the harness's in-memory SQLite cannot.
The ``_real_server_settings`` fixture in this directory's conftest overrides the
harness's PREFECT_API_URL for each test so @flow calls reach the real server.

Run with:
    PREFECT_API_URL=http://192.168.2.182:4200/api venv/bin/pytest -q -m prefect_real -v
"""
from __future__ import annotations

import time
import uuid
from contextlib import ExitStack
from unittest.mock import patch

import httpx
import pytest

from tests.integration._helpers import real_api_url

pytestmark = pytest.mark.prefect_real

# ---------------------------------------------------------------------------
# Shared test data — same shape the patched orchestration internals expect
# ---------------------------------------------------------------------------
_VALID_PLAN = {
    "language": "python",
    "project_type": "script",
    "execution_mode": "generate",
    "port": 0,
    "entrypoint": "main.py",
    "files": {"main.py": "print('hi')"},
    "dependencies": [],
    "steps": [],
    "approach": "print hello",
}

_VALID_CANDIDATE = {
    "model": "m1",
    "files": {"main.py": "print('hi')"},
    "score": 9,
    "judge": {"feedback": "looks good"},
}


# ---------------------------------------------------------------------------
# Test 1 — basic reachability
# ---------------------------------------------------------------------------


def test_prefect_server_health():
    """Confirm the real Prefect server responds to /health before any flow tests."""
    r = httpx.get(real_api_url() + "/health", timeout=5.0)
    assert r.status_code == 200


# ---------------------------------------------------------------------------
# Test 2 — submit orchestrate flow and verify it appears on the real server
# ---------------------------------------------------------------------------


def test_orchestrate_flow_against_real_server():
    """Run a tiny orchestrate flow; verify it appears in the server's flow_runs list.

    Agent functions are patched at the orchestration module level (same approach
    as tests/test_orchestrate_flow.py) to avoid needing a real Ollama server or
    SSH sandbox — every code path that would call llm.ollama.requests.post is
    short-circuited by patching planner_agent.fn / generate_candidate.fn /
    sandbox_execute, so mock_ollama is unnecessary here. The Prefect client is
    pointed at the real server via the ``_real_server_settings`` autouse fixture
    in this directory's conftest.
    """
    from orchestration import OrchestrateRequest, run_orchestration

    run_id = f"real-smoke-{uuid.uuid4().hex[:8]}"

    req = OrchestrateRequest(
        project_name="real-smoke",
        deploy_target="local",
        prompt="print hi",
        language="python",
        generator_models=["m1"],
        judge_model="judge",
        planner_model="planner",
    )

    with ExitStack() as stack:
        stack.enter_context(
            patch("orchestration.planner_agent.fn", return_value=_VALID_PLAN)
        )
        stack.enter_context(
            patch("orchestration.generate_candidate.fn", return_value=_VALID_CANDIDATE)
        )
        stack.enter_context(
            patch(
                "orchestration.sandbox_execute",
                return_value={"exit_code": 0, "stdout": "hi", "error": ""},
            )
        )
        stack.enter_context(
            patch(
                "orchestration.environment_inspector",
                return_value={
                    "os": "Linux",
                    "python": "python3",
                    "node": "node",
                    "arch": "x86_64",
                },
            )
        )
        stack.enter_context(
            patch("orchestration.gather_live_context", return_value="")
        )
        stack.enter_context(
            patch("orchestration.build_full_planner_context", return_value="")
        )
        stack.enter_context(patch("orchestration.notify_run_started"))
        stack.enter_context(patch("orchestration.notify_run_complete"))
        run_orchestration(req, run_id)

    # Query the real Prefect server for the flow run we just produced.
    # Filter by flow name "orchestrate" (not by flow-run name, which is
    # auto-generated by Prefect, e.g. "eager-rat").
    r = httpx.post(
        real_api_url() + "/flow_runs/filter",
        json={"flows": {"name": {"any_": ["orchestrate"]}}, "limit": 50},
        timeout=5.0,
    )
    assert r.status_code == 200, f"filter request failed: {r.status_code} {r.text[:200]}"
    runs = r.json()
    assert any(
        run.get("parameters", {}).get("run_id") == run_id for run in runs
    ), (
        f"flow run with run_id={run_id!r} not found among {len(runs)} "
        f"returned runs (names: {[r.get('name') for r in runs[:5]]})"
    )


# ---------------------------------------------------------------------------
# Test 3 — cancel a flow run via prefect_io, verify state on real server
# ---------------------------------------------------------------------------


def test_cancel_flow_run_through_real_server():
    """Create a SCHEDULED flow run on the real server, cancel via prefect_io,
    verify the server reflects a CANCEL* state.

    Uses POST /api/flow_runs directly (not via a deployment) to avoid
    supplying the full OrchestrateRequest body that the registered deployment
    schema requires.
    """
    from prefect_io import cancel_flow_run

    flow_id = None
    # Resolve the flow_id for the "orchestrate" flow
    r = httpx.post(
        real_api_url() + "/flows/filter",
        json={"flows": {"name": {"any_": ["orchestrate"]}}, "limit": 1},
        timeout=5.0,
    )
    if r.status_code != 200 or not r.json():
        pytest.skip("No 'orchestrate' flow found on the Prefect server")
    flow_id = r.json()[0]["id"]

    # Create a SCHEDULED flow run (not via deployment — avoids required-params 409)
    r = httpx.post(
        real_api_url() + "/flow_runs",
        json={
            "flow_id": flow_id,
            "name": "cancel-smoke-i3",
            "state": {"type": "SCHEDULED", "name": "Scheduled"},
        },
        timeout=5.0,
        follow_redirects=True,
    )
    if r.status_code != 201:
        pytest.skip(
            f"Could not create flow run for cancel test "
            f"(status {r.status_code}): {r.text[:200]}"
        )
    flow_run_id = r.json()["id"]

    # cancel_flow_run uses _getreal_api_url() from config.json, which points at
    # the real LAN server (192.168.2.182:4200) regardless of harness settings.
    cancel_flow_run(flow_run_id)

    # Poll for CANCEL* — Prefect typically flips SCHEDULED→CANCELLED in
    # tens of ms locally, but a slow CI runner can stay in SCHEDULED briefly
    # before the cancel signal is processed. 5s budget at 100ms steps.
    deadline = time.time() + 5.0
    state_type = ""
    while time.time() < deadline:
        r2 = httpx.get(real_api_url() + f"/flow_runs/{flow_run_id}", timeout=5.0)
        assert r2.status_code == 200
        state_type = r2.json()["state"]["type"]
        if "CANCEL" in state_type.upper():
            break
        time.sleep(0.1)
    assert "CANCEL" in state_type.upper(), (
        f"Expected CANCEL* state within 5s, got {state_type!r}"
    )
